{
 "title": "Kafka Connectors for TxEventQ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_connect_app{job=\"kafka\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka\"},connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_total_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"kafka\", connector=~\"$connector\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Connector Status and Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connector_metrics{job=\"kafka\", status=\"running\", connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connector_metrics{job=\"kafka\", status=\"stopped\", \"$connector\"=~\"$connector\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connector_metrics{job=\"kafka\", status=\"paused\", \"$connector\"=~\"$connector\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_running_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_failed_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_paused_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_destroyed_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum by(connector) (kafka_connect_connect_worker_metrics_connector_unassigned_task_count{job=\"kafka\", connector=\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "description": "Calculates the total rate of time spent on JVM garbage collection across all garbage collector types, over a 5-minute period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc) (rate(jvm_gc_collection_seconds_sum{job=\"kafka\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=\"kafka\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Max"
    },
    {
     "expr": "sum without(area) (jvm_memory_used_bytes{job=\"kafka\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Used"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Calculates the average per-second CPU usage of a process over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\", instance=~\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connect Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Network IO Rate",
   "type": "timeseries",
   "description": "Average number of network operations (reads or writes) on all connections per  second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_network_io_rate{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "timeseries",
   "description": "Bytes per second read off all sockets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "timeseries",
   "description": "Average number of outgoing bytes sent per second to all servers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "timeseries",
   "description": "Current number of active connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_connection_count{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "timeseries",
   "description": "Connections that failed authentication",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_failed_authentication{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "timeseries",
   "description": "Average number of requests sent per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_request_rate{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "timeseries",
   "description": "Responses received and sent per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_response_rate{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "description": "Fraction of time the I/O thread spent doing I/O",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  { "title": "Rebalances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Tracks the average time (in milliseconds) that a Kafka Connect worker spends on rebalancing operations. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_rebalance_avg_time_ms{job=\"kafka\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "($instance) Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_rebalance_metrics_time_since_last_rebalance_ms{job=\"kafka\", instance=~\"$instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_avg{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Maximum size of the batches processed by the connector",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_batch_size_max{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_success_percentage{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_avg_time_ms{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset Commit Failure Percentage",
   "type": "timeseries",
   "description": "The average percentage of this task's offset commit attempts that failed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_offset_commit_failure_percentage{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Task Errors metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_failures{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_record_errors{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_records_skipped{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_metrics_total_retries{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Source Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_poll_batch_avg_time_ms{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_poll_batch_max_time_ms{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "timeseries",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_poll_rate{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write rate",
   "type": "timeseries",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_write_rate{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_active_count_avg{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_active_count_max{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write Count",
   "type": "gauge",
   "description": "The number of records output written to Kafka for this task belonging to the named source connector in this worker, since the task was last restarted. This is after transformations are applied, and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_write{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll Count",
   "type": "gauge",
   "description": "The total number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 160 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_metrics_source_record_poll{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Producer Request Sent Rate",
   "type": "timeseries",
   "description": "The number of requests sent per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate{job=\"kafka\", client_id=~\"connector-producer-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Producer Request Size Average",
   "type": "timeseries",
   "description": "The average size of requests sent.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_size_avg{job=\"kafka\", client_id=~\"connector-producer-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Producer Response Received Rate",
   "type": "timeseries",
   "description": "The number of responses received per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_response_rate{job=\"kafka\", client_id=~\"connector-producer-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Producer Request Latency Average",
   "type": "timeseries",
   "description": "Measures the average round-trip time, in milliseconds, for a batch of records sent from the Source connector to the Kafka broker. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{job=\"kafka\", client_id=~\"connector-producer-.*\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Sink Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partition Count",
     "type": "timeseries",
     "description": "The number of topic partitions assigned to this task belonging to the named sink ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_partition_count{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Average time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_avg_time_ms{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Max time",
     "type": "timeseries",
     "description": "The maximum time in milliseconds taken by this task to put a batch of sinks ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_put_batch_max_time_ms{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Read Count",
     "type": "gauge",
     "description": "The total number of records read from Kafka by this task belonging to the named sink connector in this worker, since the task was last restarted",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_read{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Active Count",
     "type": "timeseries",
     "description": "The number of records that have been read from Kafka but not yet completely committed/flushed/acknowledged by the sink task.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_active_count{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Active Count Average",
     "type": "timeseries",
     "description": "The average number of records that have been read from Kafka but not yet completely committed/flushed/acknowledged by the sink task. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_active_count_avg{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Active Max Count",
     "type": "timeseries",
     "description": "The maximum number of records that have been read from Kafka but not yet completely committed/flushed/acknowledged by the sink task. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_active_count_max{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Read Rate",
     "type": "timeseries",
     "description": "The average per-second number of records read from Kafka for this task belonging to the named sink connector in this worker. This is before transformations are applied.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_read_rate{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Send Total",
     "type": "timeseries",
     "description": "The total number of records output from the transformations and sent/put to this task belonging to the named sink connector in this worker, since the task was last restarted.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_send{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Sink Record Send Rate",
     "type": "timeseries",
     "description": "The average per-second number of records output from the transformations and sent/put to this task belonging to the named sink connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_sink_record_send_rate{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Number of Offset Commit Completions",
     "type": "timeseries",
     "description": "The total number of offset commit completions that were completed successfully.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_offset_commit_completion{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset Commit Completion Rate",
     "type": "timeseries",
     "description": "The average per-second number of offset commit completions that were completed successfully.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_metrics_offset_commit_completion_rate{job=\"kafka\", instance=~\"$instance\", connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Consumer Request Sent Rate",
     "type": "timeseries",
     "description": "The number of requests sent per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_rate{job=\"kafka\", instance=~\"$instance\", client_id=~\"connector-consumer-.*\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Request Size Average",
     "type": "timeseries",
     "description": "The average size of requests sent\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_size_avg{job=\"kafka\", client_id=~\"connector-consumer-.*\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Response Rate",
     "type": "timeseries",
     "description": "The number of responses received per second ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_response_rate{job=\"kafka\", client_id=~\"connector-consumer-.*\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Fetch Latency Average",
     "type": "timeseries",
     "description": "Represents the average time, in milliseconds, taken by the Kafka consumer within the sink connector to fetch a batch of records from a Kafka topic partition.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{job=\"kafka\", client_id=~\"connector-consumer-.*\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    },
    {
     "title": "Consumer Fetch Rate",
     "type": "timeseries",
     "description": "Measures the number of fetches per second for the sink connector to asks the Kafka brokers for new batches of records to process.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{job=\"kafka\", client_id=~\"connector-consumer-.*\"}",
       "legendFormat": "{{client_id}}"
      }
     ]
    }
   ]
  }
 ]
}